$kind: http-request
name: 'POST /api/config/retention'
description: |-
  Set the retention window.
method: POST
url: '{{baseUrl}}/api/config/retention'
order: 8000
headers:
  - key: 'Content-Type'
    value: 'application/json'
body:
  type: json
  content: |-
    {}
