$kind: http-request
name: 'POST /api/config/usage-throttling'
description: |-
  Change usage throttling.
method: POST
url: '{{baseUrl}}/api/config/usage-throttling'
order: 16000
headers:
  - key: 'Content-Type'
    value: 'application/json'
body:
  type: json
  content: |-
    {}
