import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

interface WorkerSpec {
	entrypoint: string;
	output: string;
	exportName: string;
}

const PROJECT_ROOT = join(import.meta.dir, "../..");
const DATABASE_SOURCE = join(PROJECT_ROOT, "packages/database/src");
const WORKERS: WorkerSpec[] = [
	{
		entrypoint: join(DATABASE_SOURCE, "vacuum-worker.ts"),
		output: join(DATABASE_SOURCE, "inline-vacuum-worker.ts"),
		exportName: "EMBEDDED_VACUUM_WORKER_CODE",
	},
	{
		entrypoint: join(DATABASE_SOURCE, "incremental-vacuum-worker.ts"),
		output: join(DATABASE_SOURCE, "inline-incremental-vacuum-worker.ts"),
		exportName: "EMBEDDED_INCREMENTAL_VACUUM_WORKER_CODE",
	},
	{
		entrypoint: join(DATABASE_SOURCE, "integrity-check-worker.ts"),
		output: join(DATABASE_SOURCE, "inline-integrity-check-worker.ts"),
		exportName: "EMBEDDED_INTEGRITY_CHECK_WORKER_CODE",
	},
];

async function bundleWorker(spec: WorkerSpec): Promise<string> {
	const result = await Bun.build({
		entrypoints: [spec.entrypoint],
		minify: true,
		target: "bun",
	});
	if (!result.success || result.outputs.length !== 1) {
		const diagnostics = result.logs.map((log) => log.message).join("\n");
		throw new Error(
			`failed to bundle ${spec.entrypoint}${diagnostics ? `\n${diagnostics}` : ""}`,
		);
	}

	const bundled = await result.outputs[0].text();
	const encoded = Buffer.from(bundled).toString("base64");
	return `// Generated by apps/cli/prepare-workers.ts with the pinned release Bun runtime.\n// Regenerate and commit this file whenever its worker source changes.\nexport const ${spec.exportName} = "${encoded}";\n`;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
	let existing = "";
	try {
		existing = await readFile(path, "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
			throw error;
		}
	}
	if (existing !== content) {
		await writeFile(path, content);
	}
}

/** Generate every database worker module before typecheck or compilation. */
export async function prepareEmbeddedWorkers(): Promise<void> {
	const generated = await Promise.all(
		WORKERS.map(async (worker) => ({
			worker,
			content: await bundleWorker(worker),
		})),
	);
	for (const { worker, content } of generated) {
		await writeIfChanged(worker.output, content);
	}
}

if (import.meta.main) {
	await prepareEmbeddedWorkers();
}
